#!/usr/bin/env python3
"""Derive a local build workflow from the documentation deployment workflow."""

from pathlib import Path
import re


def preview_workflow(source):
    """Preserve the build steps and remove GitHub Pages integration."""
    boundary = "    - name: Setup Pages\n"
    if source.count(boundary) != 1:
        raise ValueError("Expected one 'Setup Pages' step in doxygen.yml")
    preview = source.split(boundary, 1)[0]
    if "    - name: Build landing page\n" not in preview:
        raise ValueError("Expected the landing page build before 'Setup Pages'")

    replacements = (
        (r"^name: .*\n", "name: Doxygen local preview\n"),
        (r"^  deploy:\n", "  preview:\n"),
        (r"^    if:.*\n", ""),
        (r"^    environment:\n(?:^      .*\n)+", ""),
        (r"^    permissions:\n(?:^      .*\n)+",
         "    permissions:\n      contents: read\n"),
        (r"^    - name: Checkout current ccpp-physics code\n"
         r"(?:^(?!    - name:).*\n)*", ""),
    )
    for pattern, replacement in replacements:
        preview, count = re.subn(pattern, replacement, preview, flags=re.MULTILINE)
        if count != 1:
            raise ValueError("Unexpected doxygen.yml layout for {!r}".format(pattern))

    # act skips the current-repository checkout when --bind is set. Read its
    # documentation configuration directly from the mounted working tree.
    preview = preview.replace("$GITHUB_WORKSPACE/ccpp_repo/", "$GITHUB_WORKSPACE/")
    # Keep the SCM checkout and output below the ignored local build directory.
    prefix = "tools/.build/doxygen"
    preview = preview.replace("scm_repo", prefix + "/scm_repo")
    preview = preview.replace(
        "$GITHUB_WORKSPACE/physics/docs/html", "$GITHUB_WORKSPACE/" + prefix + "/site"
    )
    # Clear the previous output inside the container, where files from earlier
    # act runs are writable even when Docker created them as root on Linux.
    prepare = (
        "    - name: Prepare local site output\n"
        "      run: |\n"
        '        rm -rf "$GITHUB_WORKSPACE/' + prefix + '/site"\n'
        '        mkdir -p "$GITHUB_WORKSPACE/' + prefix + '/site"\n\n'
    )
    if preview.count("    steps:\n") != 1:
        raise ValueError("Expected one steps list in doxygen.yml")
    preview = preview.replace("    steps:\n", "    steps:\n\n" + prepare, 1)
    return "# Generated by tools/prepare_doxygen.py; do not edit.\n" + preview


def main():
    repository = Path(__file__).resolve().parent.parent
    source = repository / ".github/workflows/doxygen.yml"
    output = repository / "tools/.build/doxygen/workflow.yml"
    preview = preview_workflow(source.read_text(encoding="utf-8"))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(preview, encoding="utf-8")
    print("Generated tools/.build/doxygen/workflow.yml (builds only; no deployment)")


if __name__ == "__main__":
    main()
